Repository gentleeduck/ui, pull requests merged in 2025-03, with the labels that each got.

#46 fix(tailwind): update content paths in configuration files for improved class inclusion
  apps/docs/tailwind.config.ts
  tooling/tailwind/base.ts
  tooling/tailwind/docs.ts
  tooling/tailwind/web.ts
Labels: bug, enhancement

#49 perf(docs): refactor sidebar navigation for improved performance
  apps/docs/.velite/docs.json
  apps/docs/components/docs-side-bar.tsx
Labels: documentation, enhancement

#90 78 button
  .vscode/settings.json
  apps/docs/.velite/docs.json
  apps/docs/components/copy-button/copy-button.tsx
  packages/benchmark/image.png
  packages/benchmark/package.json
  packages/benchmark/postcss.config.cjs
  packages/benchmark/src/App.tsx
  packages/benchmark/src/button/README.md
  packages/benchmark/src/button/duck.tsx
  packages/benchmark/src/button/image-1.png
  packages/benchmark/src/button/image-2.png
  packages/benchmark/src/button/image-3.png
  packages/benchmark/src/button/image-4.png
  packages/benchmark/src/button/image-5.png
  packages/benchmark/src/button/native.tsx
  packages/benchmark/src/style.css
  packages/benchmark/tailwind.config.ts
  packages/benchmark/vite.config.ts
  packages/registry-ui-duckui/src/button/button.constants.ts
  packages/registry-ui-duckui/src/button/button.tsx
  pnpm-lock.yaml
Labels: documentation, enhancement, good first issue, benchmark

#97 Feat/duck benchmark
  packages/duck-benchmark/package.json
  packages/duck-benchmark/postcss.config.js
  packages/duck-benchmark/src/commands/init/init.lib.ts
  packages/duck-benchmark/src/utils/compile-benchmark/compile-benchmark.constants.ts
  packages/duck-benchmark/src/utils/compile-benchmark/compile-benchmark.libs.tsx
  packages/duck-benchmark/src/utils/compile-benchmark/compile-benchmark.tsx
  packages/duck-benchmark/src/utils/compile-benchmark/compile-benchmark.types.ts
  packages/duck-benchmark/src/utils/compile-benchmark/index.ts
  packages/duck-benchmark/src/utils/list-files/index.ts
  packages/duck-benchmark/src/utils/list-files/list-files.dto.ts
  packages/duck-benchmark/src/utils/list-files/list-files.ts
  packages/duck-benchmark/src/utils/list-files/list-files.types.ts
  packages/duck-benchmark/tsconfig.json
  packages/sandbox-test/run.sh
  pnpm-lock.yaml
Labels: enhancement, benchmark

#100 feat(duckui-cli): done with ts preflight and duckuiconfig
  apps/docs/public/schema.json
  packages/duck-ui/src/commands/init/init.lib.ts
  packages/duck-ui/src/utils/get-project-config/get-project-config.ts
  packages/duck-ui/src/utils/get-project-info/get-project-info.ts
  packages/duck-ui/src/utils/get-project-type/get-project-type.constants.ts
  packages/duck-ui/src/utils/get-project-type/get-project-type.dto.ts
  packages/duck-ui/src/utils/get-project-type/get-project-type.lib.ts
  packages/duck-ui/src/utils/get-project-type/get-project-type.ts
  packages/duck-ui/src/utils/get-project-type/get-project-type.types.ts
  packages/duck-ui/src/utils/get-project-type/index.ts
  packages/duck-ui/src/utils/get-registry/get-registry.lib.ts
  packages/duck-ui/src/utils/index.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-configs.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.constants.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.dto.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.libs.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-tailwindcss/pref-light-tailwindcss.lib.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-tailwindcss/pref-light-tailwindcss.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-typescript/preflight-typescript.constants.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-typescript/preflight-typescript.libs.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-typescript/preflight-typescript.ts
  packages/duck-ui/src/utils/transformers/transformers.ts
  packages/duck-ui/src/utils/url-mutating/url-mutating.ts
  packages/duck-ui/test/duck-ui.config.json
  packages/duck-ui/test/duck-ui.config.ts
  packages/duck-ui/test/index.d.ts
  packages/duck-ui/test/index.js
  packages/duck-ui/test/index.js.map
  packages/duck-ui/test/package.json
  packages/duck-ui/test/postcss.config.js
  packages/duck-ui/test/src/tsconfig.json
  packages/duck-ui/test/tailwind.config.ts
  packages/duck-ui/test/tsconfig.json
  packages/duck-ui/tsconfig.json
  pnpm-lock.yaml
Labels: benchmark, feature

#102 feat(duckui-cli): done with the init of the preflights
  packages/duck-ui/src/utils/get-package-manager/get-package-manager.ts
  packages/duck-ui/src/utils/index.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-configs.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.constants.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.libs.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-tailwindcss/pref-light-tailwindcss.constants.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-tailwindcss/pref-light-tailwindcss.lib.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-tailwindcss/pref-light-tailwindcss.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-typescript/preflight-typescript.constants.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-typescript/preflight-typescript.libs.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-typescript/preflight-typescript.ts
  packages/duck-ui/src/utils/prompts-options/propmpts-options.ts
  packages/duck-ui/src/utils/text-styling/highlighter.ts
  packages/duck-ui/src/utils/text-styling/logger.ts
  packages/duck-ui/src/utils/transformers/index.ts
  packages/duck-ui/src/utils/transformers/transformers.ts
  packages/duck-ui/test/duck-ui.config.json
  packages/duck-ui/test/package.json
  packages/duck-ui/test/src/styles.css
  packages/duck-ui/test/style.css
  packages/duck-ui/test/tsconfig.json
  packages/duck-ui/test/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement, feature

#103 feat(duckui-cli): done with the reg_idx, reg_comp and working on
  apps/docs/__ui_registry__/index.tsx
  apps/docs/public/duck-ui/components/button.json
  packages/duck-ui/package.json
  packages/duck-ui/src/commands/init/init.lib.ts
  packages/duck-ui/src/main/main.constants.ts
  packages/duck-ui/src/utils/get-registry/get-registry.dto.ts
  packages/duck-ui/src/utils/get-registry/get-registry.ts
  packages/registers/registry-colors/registry-colors.dto.ts
  packages/registry-build-duckui/build-registry-build-colors/build-registry-build-colors.constants.ts
  packages/registry-build-duckui/build-registry-build-colors/build-registry-build-colors.lib.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#107 Feat/duckui cli
  packages/duck-ui/src/commands/add/add.libs.ts
  packages/duck-ui/src/commands/init/init.constants.ts
  packages/duck-ui/src/utils/checkers/checkers.ts
  packages/duck-ui/src/utils/checkers/index.ts
  packages/duck-ui/src/utils/get-project-config/get-project-config.constants.ts
  packages/duck-ui/src/utils/get-project-config/get-project-config.dto.ts
  packages/duck-ui/src/utils/get-project-config/get-project-config.ts
  packages/duck-ui/src/utils/get-project-config/index.ts
  packages/duck-ui/src/utils/get-project-info/get-project-info.constants.ts
  packages/duck-ui/src/utils/get-project-info/get-project-info.dto.ts
  packages/duck-ui/src/utils/get-project-info/get-project-info.ts
  packages/duck-ui/src/utils/get-project-info/index.ts
  packages/duck-ui/src/utils/get-registry/get-registry.ts
  packages/duck-ui/src/utils/index.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.constants.ts
  packages/duck-ui/src/utils/preflight-configs/preflight-duckui/preflight-duckui.dto.ts
  packages/duck-ui/src/utils/registry-mutation/index.ts
  packages/duck-ui/src/utils/registry-mutation/registry-mutation.lib.ts
  packages/duck-ui/src/utils/registry-mutation/registry-mutation.ts
  packages/duck-ui/src/utils/registry-mutation/registry-mutation.types.ts
  packages/duck-ui/src/utils/resolve-import/index.ts
  packages/duck-ui/src/utils/resolve-import/resolve-import.ts
  packages/duck-ui/src/utils/spinner.ts
  packages/duck-ui/src/utils/url-mutating/index.ts
  packages/duck-ui/src/utils/url-mutating/url-mutating.dto.ts
  packages/duck-ui/src/utils/url-mutating/url-mutating.ts
  packages/duck-ui/test/duck-ui.config.json
  packages/duck-ui/test/package.json
  packages/duck-ui/test/src/ui/button/button.constants.ts
  packages/duck-ui/test/src/ui/button/button.tsx
  packages/duck-ui/test/src/ui/button/button.types.ts
  packages/duck-ui/test/src/ui/button/index.ts
  packages/duck-ui/test/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, feature
