Repository gentleeduck/ui, pull requests merged in 2025-06, with the labels that each got.

#141 refactor(textarea): some fixes, types
  apps/docs/components/layouts/command-menu/command-menu.tsx
  packages/benchmark/src/App.tsx
  packages/benchmark/src/duck/tabs/duck.tsx
  packages/benchmark/src/duck/textarea/duck.tsx
  packages/benchmark/src/duck/textarea/textarea.tsx
  packages/benchmark/src/example/dialog.tsx
  packages/registry-ui-duckui/src/checkbox/checkbox.tsx
  packages/registry-ui-duckui/src/dialog/dialog.tsx
  packages/registry-ui-duckui/src/dialog/style.css
  packages/registry-ui-duckui/src/switch/switch.tsx
  packages/registry-ui-duckui/src/textarea/textarea.tsx
  packages/registry-ui-duckui/src/toggle/toggle.constants.ts
  packages/registry-ui-duckui/src/toggle/toggle.tsx
Labels: ✨ enhancement, 🚀 benchmark, 🧩 feature

#176 chore(all): merge
  apps/docs/app/(app)/layout.tsx
  apps/docs/app/layout.tsx
  packages/aria-feather/src/dialog/dialog.types.ts
  packages/aria-feather/src/popover/popover.hooks.ts
  packages/aria-feather/src/popover/popover.tsx
  packages/aria-feather/src/popover/popover.types.ts
  packages/registry-ui-duckui/index.ts
  packages/registry-ui-duckui/src/command/command.hooks.ts
  packages/registry-ui-duckui/src/command/command.tsx
  packages/registry-ui-duckui/src/dropdown-menu/_dropdown-menu.tsx
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.hooks.ts
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.libs.ts
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.tsx
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.types.ts
  packages/registry-ui-duckui/src/dropdown-menu/index.ts
  packages/registry-ui-duckui/src/popover/popover.tsx
  packages/registry-ui-duckui/src/select/select.hooks.ts
  packages/registry-ui-duckui/src/select/select.libs.ts
  packages/registry-ui-duckui/src/select/select.tsx
  packages/registry-ui-duckui/src/select/select.types.ts
Labels: 🐛 bug, 🔁 duplicate, ✨ enhancement, 🐣 good first issue, 🧩 feature

#178 refactor(popover): unify popover and dropdown behavior across components
  apps/docs/app/(app)/layout.tsx
  packages/aria-feather/src/popover/popover.hooks.ts
  packages/aria-feather/src/popover/popover.tsx
  packages/registry-ui-duckui/src/command/command.hooks.ts
  packages/registry-ui-duckui/src/command/command.libs.ts
  packages/registry-ui-duckui/src/dropdown-menu/_dropdown-menu.tsx
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.hooks.ts
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.libs.ts
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.tsx
  packages/registry-ui-duckui/src/dropdown-menu/dropdown-menu.types.ts
  packages/registry-ui-duckui/src/menubar/menubar.tsx
  packages/registry-ui-duckui/src/popover/popover.tsx
Labels: 🐛 bug, 🔁 duplicate, ✨ enhancement, 🐣 good first issue, 🧩 feature

#177 Revamped Checkers Components: Custom SVG Indicators, Accessibility, Styles & Animations
  apps/benchmark/sonda-report.html
  apps/benchmark/src/App.tsx
  apps/benchmark/src/duck/checkbox/duck.tsx
  apps/benchmark/src/duck/radio-group/duck.tsx
  apps/benchmark/src/duck/switch/duck.tsx
  apps/benchmark/src/example/accordion.tsx
  apps/benchmark/vite.config.ts
  packages/aria-feather/package.json
  packages/aria-feather/src/checkers/checkers.tsx
  packages/aria-feather/src/checkers/index.ts
  packages/duck-motion/anim.ts
  packages/registry-ui-duckui/src/accordion/accordion.tsx
  packages/registry-ui-duckui/src/checkbox/_checkbox.tsx
  packages/registry-ui-duckui/src/checkbox/checkers.constants.ts
  packages/registry-ui-duckui/src/checkbox/index.ts
  packages/registry-ui-duckui/src/radio-group/_radio-group.tsx
  packages/registry-ui-duckui/src/radio-group/index.ts
  packages/registry-ui-duckui/src/slider/slider.tsx
  packages/registry-ui-duckui/src/switch/switch.tsx
  pnpm-lock.yaml
Labels: 🐛 bug, 🔁 duplicate, ✨ enhancement, 🧩 feature
